### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/COPIERTemplate.jl#22]
It is unclear whether Windows is supported.
The CI fails with

```plaintext
"C:\Program Files\Git\bin\git.exe" checkout --progress --force refs/remotes/pull/21/merge
  Error: error: invalid path '{% if License == "Apache-2.0" %}LICENSE{% endif %}.jinja'
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

Help is welcome.

**Comment by datejada** [comment]
I found the error cause of the error, but I don't know how to solve it correctly.

So, the error message indicates that the `git checkout -f HEAD` command failed due to an invalid path. The path in question is `template/{% if License == "Apache-2.0" %}LICENSE{% endif %}.jinja`. This path contains a syntax that is not valid in a file path for Windows.

This error appears when the Copier tool is trying to clone the repository and checkout to the HEAD commit, but it encounters a file with a name that is not valid on Windows.

One possible solution to fix this issue is to modify the copier.yml file such as skipping this file for Windows and copying another one that has a valid name for Windows OS.

**Comment by datejada** [comment]
It is the same error, I tried that and it seems that the copier also attempts to clone the repo and then fails due to the file name that has the symbols that Windows doesn't like 😞 

<img width="668" alt="image" src="https://github.com/abelsiqueira/COPIERTemplate.jl/assets/12887482/3c4ef07b-2a68-46a0-9401-ae666faa22c8">

**Comment by abelsiqueira** [comment]
Thanks for checking. That helped figure out the issue (I hope). Since copier should work on Windows, I went back to check the docs, and the issue are the double-quotes. #39 should fix it.

**Comment by abelsiqueira** [comment]
@datejada, thanks for the help. It should work on Windows on version 0.2.3 now.
